name: Docs Format Check

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.js"
      - "**.jsx"
      - "**.ts"
      - "**.tsx"
      - "**.json"
      - "**.md"
      - "**.yml"
      - "**.yaml"
      - "**.astro"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/format.yml"

permissions:
  contents: read

jobs:
  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check
